name: Android CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: 17
        distribution: 'zulu'
    - name: Cache Gradle packages
      uses: actions/cache@v4
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
        restore-keys: ${{ runner.os }}-gradle
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: |
        ./gradlew assembleRelease --stacktrace
        ./gradlew bundleRelease --stacktrace
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        draft: true
        files: |
          app/build/outputs/apk/release/app-release-unsigned.apk
          app/build/outputs/apk/release/app-release-unsigned.aab
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

