name: Android CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: gradle
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: |
        ./gradlew assembleRelease --stacktrace
        ./gradlew bundleRelease --stacktrace
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        draft: true
        files: |
          app/build/outputs/apk/release/app-release-unsigned.apk
          app/build/outputs/apk/release/app-release-unsigned.aab
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

